apiVersion: apps/v1
kind: Deployment
metadata:
  name: auth-service
spec:
  replicas: 2
  selector:
    matchLabels:
      app: auth-service
  template:
    metadata:
      labels:
        app: auth-service
    spec:
      containers:
        - name: auth-service
          image: auth-service:v0  # Imagen anterior para hacer el rollback
          imagePullPolicy: Never  # No intentar descargar la imagen
          ports:
            - containerPort: 3000
