apiVersion: v1
kind: Service
metadata:
  name: auth-service-lb
  labels:
    app: auth-service
spec:
  selector:
    app: auth-service  # Esta etiqueta debe coincidir con las etiquetas de tus pods
  ports:
    - protocol: TCP
      port: 80          # Puerto del servicio
      targetPort: 3000   # Puerto del contenedor (ajustado a lo que has especificado en tus pods)
  type: LoadBalancer     # Esto expone el servicio usando un LoadBalancer
