apiVersion: v1
kind: Secret
metadata:
  name: my-secret
  namespace: default
type: Opaque
data:
  username: dXNlcm5hbWU=  # Base64 encoded
  password: cGFzc3dvcmQ=  # Base64 encoded
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: security-service-account
  namespace: default
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  namespace: default
  name: security-role
rules:
  - apiGroups: [""]
    resources: ["secrets"]
    verbs: ["get", "list", "create", "delete"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: security-role-binding
  namespace: default
subjects:
  - kind: ServiceAccount
    name: security-service-account
    namespace: default
roleRef:
  kind: Role
  name: security-role
  apiGroup: rbac.authorization.k8s.io
