---
apiVersion: v1
kind: Namespace
metadata:
  name: auth-namespace

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: auth-service
  namespace: auth-namespace
spec:
  replicas: 2
  selector:
    matchLabels:
      app: auth-service
  template:
    metadata:
      labels:
        app: auth-service
    spec:
      containers:
        - name: auth-service
          image: usuario/auth-service:latest  # Reemplaza con la imagen correcta
          ports:
            - containerPort: 8080
          env:
            - name: DATABASE_URL
              value: "mysql://user:password@db-host/auth-db"  # Ajusta los valores

---
apiVersion: v1
kind: Service
metadata:
  name: auth-service
  namespace: auth-namespace
spec:
  selector:
    app: auth-service
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8080
  type: ClusterIP
