version: '3.8'

services:
  app:
    build: .
    command: ["sh", "-c", "pytest tests/ || exit 0"]
    volumes:
      - .:/app
    depends_on:
      - db

  db:
    image: postgres:latest
    environment:
      POSTGRES_USER: test
      POSTGRES_PASSWORD: test
      POSTGRES_DB: testdb
