name: CD Pipeline

on:
  workflow_run:
    workflows: ["CI Pipeline"]
    types:
      - completed

jobs:
  deploy_infra:
    runs-on: ubuntu-latest
    steps:
      - name: Check out the code
        uses: actions/checkout@v3

      - name: Install Terraform
        uses: hashicorp/setup-terraform@v2
        with:
          terraform_version: 1.6.1

      - name: Initialize Terraform
        run: |
          cd terraform
          rm -rf .terraform
          terraform init -reconfigure -upgrade

      - name: Apply Terraform Configuration
        run: |
          cd terraform
          terraform apply -auto-approve || (terraform init -force-copy && terraform apply -auto-approve)

  deploy_k8s:
    runs-on: ubuntu-latest
    needs: deploy_infra
    steps:
      - name: Check out the code
        uses: actions/checkout@v3

      - name: Install kubectl
        run: |
          curl -LO "https://dl.k8s.io/release/$(curl -L -s https://dl.k8s.io/release/stable.txt)/bin/linux/amd64/kubectl"
          chmod +x kubectl
          sudo mv kubectl /usr/local/bin/

      - name: Install Minikube
        run: |
          curl -Lo minikube https://storage.googleapis.com/minikube/releases/latest/minikube-linux-amd64
          chmod +x minikube
          sudo mv minikube /usr/local/bin/

      - name: Start Minikube
        run: |
          minikube start --driver=docker
          minikube addons enable metrics-server

      - name: Wait for Kubernetes API to be Ready
        run: |
          for i in {1..10}; do
            if kubectl cluster-info; then
              echo "Kubernetes API Server está listo."
              break
            fi
            echo "Esperando que Kubernetes esté listo..."
            sleep 10
          done

      - name: Apply Namespace
        run: |
          kubectl create namespace auth-namespace || echo "Namespace ya existe"
          kubectl get namespace auth-namespace --no-headers

      - name: Apply Kubernetes Configurations
        run: |
          cd servicios/auth-service
          kubectl apply -f deployment.yml --validate=false

  ansible:
    runs-on: ubuntu-latest
    needs: deploy_k8s
    steps:
      - name: Check out the code
        uses: actions/checkout@v3

      - name: Install Minikube if not installed
        run: |
          if ! command -v minikube &> /dev/null; then
            echo "Minikube no encontrado. Instalando..."
            curl -Lo minikube https://storage.googleapis.com/minikube/releases/latest/minikube-linux-amd64
            chmod +x minikube
            sudo mv minikube /usr/local/bin/
          else
            echo "Minikube ya está instalado."
          fi

      - name: Verify and Restart Minikube if needed
        run: |
          if ! minikube status | grep -q "Running"; then
            echo "Minikube no está corriendo. Intentando iniciarlo..."
            minikube start --driver=docker
          fi
          kubectl config use-context minikube
          kubectl cluster-info

      - name: Wait for Kubernetes to be Ready
        run: |
          for i in {1..10}; do
            if kubectl get nodes; then
              echo "Kubernetes está listo."
              break
            fi
            echo "Esperando a que Kubernetes esté listo..."
            sleep 10
          done

      - name: Install Ansible
        run: |
          sudo apt-get update
          sudo apt-get install -y ansible

      - name: Configure sudo for Ansible
        run: |
          echo "$(whoami) ALL=(ALL) NOPASSWD: ALL" | sudo tee /etc/sudoers.d/$(whoami)

      - name: Create Namespace if not exists
        run: |
          kubectl create namespace auth-namespace --dry-run=client -o yaml | kubectl apply -f -

      - name: Verify Kubernetes Connection
        run: |
          if ! kubectl cluster-info; then
            echo "Error: No se puede conectar al API Server de Kubernetes. Abortando."
            exit 1
          fi

      - name: Run Ansible Playbook
        run: |
          ansible-playbook -i ansible/hosts.ini ansible/playbook.yml --become || (echo "Ansible falló. Verifica errores." && exit 1)

  cleanup:
    runs-on: ubuntu-latest
    if: failure()
    steps:
      - name: Check out the code
        uses: actions/checkout@v3

      - name: Terraform Destroy
        run: |
          cd terraform
          terraform destroy -auto-approve
