name: CD Pipeline

on:
  workflow_run:
    workflows: ["CI Pipeline"]
    types:
      - completed

jobs:
  deploy_infra:
    runs-on: ubuntu-latest
    steps:
      - name: Check out the code
        uses: actions/checkout@v3

      - name: Install Terraform
        uses: hashicorp/setup-terraform@v2
        with:
          terraform_version: 1.6.1

      - name: Initialize Terraform
        run: |
          cd terraform
          rm -rf .terraform
          terraform init -reconfigure -upgrade

      - name: Apply Terraform Configuration
        run: |
          cd terraform
          terraform apply -auto-approve || (terraform init -force-copy && terraform apply -auto-approve)

  deploy_k8s:
    runs-on: ubuntu-latest
    needs: deploy_infra
    steps:
      - name: Check out the code
        uses: actions/checkout@v3

      - name: Install kubectl
        run: |
          curl -LO "https://dl.k8s.io/release/$(curl -L -s https://dl.k8s.io/release/stable.txt)/bin/linux/amd64/kubectl"
          chmod +x kubectl
          sudo mv kubectl /usr/local/bin/

      - name: Install Minikube
        run: |
          curl -Lo minikube https://storage.googleapis.com/minikube/releases/latest/minikube-linux-amd64
          chmod +x minikube
          sudo mv minikube /usr/local/bin/

      - name: Start Minikube
        run: |
          minikube start --driver=docker
          minikube addons enable metrics-server

      - name: Apply Namespace
        run: |
          kubectl create namespace auth-namespace || echo "Namespace ya existe"
          kubectl get namespace auth-namespace --no-headers

      - name: Apply Kubernetes Configurations
        run: kubectl apply -f servicios/auth-service/app/deployment.yml
  ansible:
    runs-on: ubuntu-latest
    needs: deploy_k8s
    steps:
      - name: Check out the code
        uses: actions/checkout@v3

      - name: Instalar Minikube (si es necesario)
        run: |
          if ! command -v minikube &> /dev/null; then
            curl -Lo minikube https://storage.googleapis.com/minikube/releases/latest/minikube-linux-amd64
            chmod +x minikube
            sudo mv minikube /usr/local/bin/
          fi

      - name: Verificar Minikube y Kubernetes
        run: |
          minikube status || minikube start --driver=docker
          kubectl config use-context minikube
          kubectl get nodes

      - name: Esperar a que Kubernetes esté listo
        run: |
          for i in {1..10}; do
            kubectl get nodes && break
            echo "Esperando a que Kubernetes esté listo..."
            sleep 10
          done

      - name: Instalar Ansible
        run: |
          sudo apt-get update
          sudo apt-get install -y ansible

      - name: Ejecutar Ansible Playbook
        run: |
          ansible-playbook -i ansible/hosts.ini ansible/playbook.yml --become 
  cleanup:
    runs-on: ubuntu-latest
    if: failure()
    steps:
      - name: Check out the code
        uses: actions/checkout@v3

      - name: Terraform Destroy
        run: |
          cd terraform
          terraform destroy -auto-approve
