name: CI Pipeline

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  validate:
    runs-on: ubuntu-latest
    steps:
      - name: Check out the code
        uses: actions/checkout@v3

      - name: Install Minikube
        run: |
          curl -Lo minikube https://storage.googleapis.com/minikube/releases/latest/minikube-linux-amd64
          chmod +x minikube
          sudo mv minikube /usr/local/bin/

      - name: Start Minikube
        run: |
          sudo minikube start --driver=docker
          mkdir -p ~/.minikube/profiles/minikube/
          minikube kubectl -- get pods -A

      - name: Set up Terraform
        uses: hashicorp/setup-terraform@v1
        with:
          terraform_version: 1.0.0

      - name: Initialize Terraform
        run: |
          cd terraform
          terraform init -upgrade

      - name: Fix plugin permissions
        run: |
          cd terraform
          chmod -R 755 .terraform || echo "No .terraform directory, skipping chmod"

      - name: Format Terraform files
        run: |
          cd terraform
          terraform fmt -recursive

      - name: Validate Terraform configuration
        run: |
          cd terraform
          terraform validate

  docker:
    runs-on: ubuntu-latest
    needs: validate
    steps:
      - name: Check out the code
        uses: actions/checkout@v3

      - name: Install Docker-Compose
        run: sudo apt-get update && sudo apt-get install -y docker-compose

      - name: Log in to Docker
        env:
          DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
          DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}
        run: |
          echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin

      - name: Build and Push Docker image
        run: |
          docker build -t myapp .
          docker push myapp

  test:
    runs-on: ubuntu-latest
    needs: docker
    steps:
      - name: Check out the code
        uses: actions/checkout@v3

      - name: Install Docker-Compose
        run: sudo apt-get update && sudo apt-get install -y docker-compose

      - name: Run Tests
        run: |
          docker-compose -f docker-compose.test.yml up --build
          docker-compose -f docker-compose.test.yml down
