name: CI Pipeline

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  validate:
    runs-on: ubuntu-latest
    steps:
      - name: Check out the code
        uses: actions/checkout@v3

      - name: Set up Docker permissions
        run: |
          sudo usermod -aG docker $USER
          newgrp docker

      - name: Install Minikube
        run: |
          curl -Lo minikube https://storage.googleapis.com/minikube/releases/latest/minikube-linux-amd64
          chmod +x minikube
          sudo mv minikube /usr/local/bin/

      - name: Start Minikube
        run: minikube start --driver=docker

      - name: Verify Minikube
        run: minikube kubectl -- get pods -A

      - name: Set up Terraform
        uses: hashicorp/setup-terraform@v1
        with:
          terraform_version: 1.0.0

      - name: Initialize Terraform
        run: |
          cd terraform
          terraform init -upgrade

      - name: Fix plugin permissions
        run: |
          cd terraform
          chmod -R 755 .terraform || echo "No .terraform directory, skipping chmod"

      - name: Format Terraform files
        run: |
          cd terraform
          terraform fmt -recursive

      - name: Validate Terraform configuration
        run: |
          cd terraform
          terraform validate
  docker:
    runs-on: ubuntu-latest
    needs: validate
    steps:
      - name: Check out the code
        uses: actions/checkout@v3

      - name: Verify Dockerfile exists
        run: |
          if [ ! -f servicios/auth-service/Dockerfile ]; then
            echo "Dockerfile not found in servicios/auth-service/" >&2
            exit 1
          fi

      - name: Install Docker-Compose
        run: sudo apt-get update && sudo apt-get install -y docker-compose

      - name: Log in to Docker
        env:
          DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
          DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}
        run: |
          echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin

      - name: Build and Push Docker image
        run: |
          docker build -t myapp servicios/auth-service/
          docker run -d --name myapp_container myapp
  test:
    runs-on: ubuntu-latest
    needs: docker
    steps:
      - name: Check out the code
        uses: actions/checkout@v3

      - name: Install Docker-Compose
        run: sudo apt-get update && sudo apt-get install -y docker-compose

      - name: Run Tests
        run: |
          docker-compose -f servicios/auth-service/docker-compose.test.yml up --build -d
          sleep 10  # Asegura que los servicios están arriba antes de correr los tests
          docker logs $(docker ps -aqf "name=auth-service_app_1" || docker ps -aq | head -n 1) # Ver logs del contenedor de pruebas
          docker-compose -f servicios/auth-service/docker-compose.test.yml down
